version: "3"
services:
  mew: # local instance of myetherwallet
    build:
      context: ./services/mew
    ports:
    - 8080:80

  ganache:
    image: trufflesuite/ganache-cli
    command:
    - --mnemonic="candy maple cake sugar pudding cream honey rich smooth crumble sweet treat"
    - --blocktime=5
    ports:
    - 8545:8545
    - 65520:8545

  iryo:
    build:
      context: ./
      dockerfile: Dockerfile.go
    command:
    - go
    - run
    - main.go
    - server.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/iryo
    environment:
    - ETH_PRIVATE=c87509a1c067bbde78beb793e6fa76530b6382a4c0241e5e4a9ec0a0f44dc0d3
    - ETH_ADDR=http://ganache:8545
    - IRYO_ADDR=0.0.0.0:8000
    - DEBUG=1

  patient1:
    build:
      context: ./
      dockerfile: Dockerfile.go
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/patient
    environment:
    - ETH_PRIVATE=ae6ae8e5ccbfb04590405997ee2d52d2b330726137b875053c36d94e974d162f
    - IRYO_ADDR=iryo:8000
    - ETH_ADDR=http://ganache:8545
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9001:9000

  patient2:
    build:
      context: ./
      dockerfile: Dockerfile.go
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/patient
    environment:
    - ETH_PRIVATE=0dbbe8e4ae425a6d2687f1a7e3ba17bc98c673636790f1b8ad91193c05875ef1
    - IRYO_ADDR=iryo:8000
    - ETH_ADDR=http://ganache:8545
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9002:9000

  doctor:
    build:
      context: ./
      dockerfile: Dockerfile.go
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/doctor
    environment:
    - ETH_PRIVATE=c88b703fb08cbea894b6aeff5a544fb92e78a18e19814cd85da83b71f772aa6c
    - IRYO_ADDR=iryo:8000
    - ETH_ADDR=http://ganache:8545
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9003:9000
