version: "3"
services:
  nodeos:
    container_name: server
    image: eosio/eos:v1.1.0
    command: nodeosd.sh -e --http-alias=server:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    ports:
    - 8888:8888

## Create master account
  cleos:
    image: eosio/eos-dev:v1.1.0
    command:
    - /bin/bash
    - -c
    - |
      cleos wallet create
      cleos wallet import --private-key $$EOS_PRIVATE
      cleos wallet import --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 #default eosio account private key
      cleos -u $$EOS_API create account eosio master $$EOS_PUBLIC
      eosiocpp -g iryo.abi iryo.cpp
      eosiocpp -o iryo.wast iryo.cpp
    volumes:
    - ./contract:/contract
    working_dir: /contract
    environment:
    - EOS_API=${EOS_NODE} # url on which nodeos is running
    - EOS_PRIVATE=${EOS_PRIVATE_KEY} # key used to sign master account
    - EOS_PUBLIC=${EOS_PUBLIC_KEY} # key used to create master account (public key of $EOS_PRIVATE)
    tty: true
    depends_on:
    - nodeos
## Cleos interface
  tools:
    image: eosio/eos-dev:v1.1.0
    command:
    - bash
    environment:
    - EOS_API=${EOS_NODE} # url on which nodeos is running
    tty: true
## Deploy contract
  deploy:
    image: golang:1.10-alpine
    command:
    - go
    - run
    - main.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/deploy_eos_contract
    environment:
    - EOS_API=${EOS_NODE}
    - EOS_ACCOUNT=${EOS_ACCOUNT} # create accounts using this one
    - EOS_CONTRACT_ACCOUNT=${EOS_CONTRACT_ACCOUNT} # account to create and deploy the contract
    - EOS_CONTRACT_NAME=${EOS_CONTRACT_NAME}  # name of contract
    - EOS_TOKEN_ACCOUNT=iryo.token #name of account to deploy token to
    - EOS_TOKEN_NAME=eosio.token # name of token contract
    - EOS_PRIVATE=5KRuLTUU5pzPBhVPv2JkgXGtRoCM8g36PRCAxaCANYwJ7DH15tn # key used to sign master account
  api:
    image: golang:1.10-alpine
    command:
    - go
    - run
    - main.go
    - handlers.go
    - wshandlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    - ./.data:/data
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/api
    environment:
    - IRYO_ADDR=0.0.0.0:8000
    - EOS_API=${EOS_NODE}
    - EOS_ACCOUNT=${EOS_ACCOUNT}
    - EOS_CONTRACT_ACCOUNT=${EOS_CONTRACT_ACCOUNT}
    - EOS_TOKEN_ACCOUNT=iryo.token
    - EOS_PRIVATE=${EOS_PRIVATE_KEY} # key used to sign master account
    - EOS_ACCOUNT_FORMAT=${EOS_ACCOUNT_FORMAT} # key used to sign master account
    - EOS_REQUIRES_RAM=${EOS_REQUIRES_RAM}
    - DEBUG=1
    ports:
    - 8000:8000
  ## patient server
  patient1:
    image: golang:1.10-alpine
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/patient
    environment:
    - IRYO_ADDR=${IRYO_ADDR}
    - EOS_API=${EOS_NODE}
    - EOS_CONTRACT_ACCOUNT=${EOS_CONTRACT_ACCOUNT}
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9001:9000
  patient2:
    image: golang:1.10-alpine
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/patient
    environment:
    - IRYO_ADDR=${IRYO_ADDR}
    - EOS_API=${EOS_NODE}
    - EOS_CONTRACT_ACCOUNT=${EOS_CONTRACT_ACCOUNT}
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9002:9000
  ## Doctor
  doctor1:
    image: golang:1.10-alpine
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/doctor
    environment:
    - EOS_API=${EOS_NODE}
    - IRYO_ADDR=${IRYO_ADDR}
    - EOS_CONTRACT_ACCOUNT=${EOS_CONTRACT_ACCOUNT}
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9003:9000
  ## Doctor
  doctor2:
    image: golang:1.10-alpine
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/doctor
    environment:
    - EOS_API=${EOS_NODE}
    - IRYO_ADDR=${IRYO_ADDR}
    - EOS_CONTRACT_ACCOUNT=${EOS_CONTRACT_ACCOUNT}
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9004:9000

volumes:
  devchain:
