version: "3"
services:
  mew: # local instance of myetherwallet
    build:
      context: ./services/mew
    ports:
    - 8080:80

  bootstrapGeth:
    image: ethereum/client-go:v1.7.3
    command: --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain='*' --networkid=1234 --rpc --rpcaddr="0.0.0.0" init /root/files/genesis.json
    volumes:
    - devchain:/root
    - ./services/geth/genesis.json:/root/files/genesis.json:ro

  geth:
    image: ethereum/client-go:v1.7.3
    command: --nodekeyhex=091bd6067cb4612df85d9c1ff85cc47f259ced4d4cd99816b14f35650f59c322 --rpcapi "db,personal,eth,net,web3" --rpccorsdomain='*' --networkid=1234 --rpc --rpcaddr="0.0.0.0" --mine --etherbase="0xe93247262a6737B0af86c647c665513e8323AD96"
    volumes:
    - devchain:/root
    - ./services/geth/password:/root/files/password:ro
    - ./services/geth/genesis.json:/root/files/genesis.json:ro
    - ./services/geth/keystore:/root/.ethereum/devchain/keystore:rw
    ports:
    - "30303:30303"
    - "30303:30303/udp"
    - "8545:8545"

  iryo:
    image: iryo/go-futurehack
    command:
    - go
    - run
    - main.go
    - server.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/iryo
    environment:
    - ETH_PRIVATE=896772721092967eb44d6c72e3ebdd97babbada1c29eace2d8c1dd7bd1f9ee99
    - ETH_ADDR=http://geth:8545
    - IRYO_ADDR=0.0.0.0:8000
    - DEBUG=1

  patient1:
    image: iryo/go-futurehack
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/patient
    environment:
    - ETH_PRIVATE=30fa8b6d85a5aa024cd3286907c96318b27217546d28232373f94cc76bb74b76
    - IRYO_ADDR=iryo:8000
    - ETH_ADDR=http://geth:8545
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9001:9000

  patient2:
    image: iryo/go-futurehack
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/patient
    environment:
    - ETH_PRIVATE=d43cd3f2c6e210fc263e6cf6ad5db8cd9eb746e206df43f5f07eaf2d2e72bac0
    - IRYO_ADDR=iryo:8000
    - ETH_ADDR=http://geth:8545
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9002:9000

  doctor:
    image: iryo/go-futurehack
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/doctor
    environment:
    - ETH_PRIVATE=188a9155c8588b67e3083834e970e8fcb40ad9fd069eae0f247d16cb8c0a8173
    - IRYO_ADDR=iryo:8000
    - ETH_ADDR=http://geth:8545
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9003:9000

volumes:
  devchain:
