version: "3"
services:
  nodeos:
    container_name: server
    image: eosio/eos:v1.1.0
    command: nodeosd.sh -e --http-alias=server:8888 --http-alias=127.0.0.1:8888 --http-alias=localhost:8888
    ports:
    - 8888:8888
    logging:
      driver: none

## Create master account
  cleos:
    image: eosio/eos:v1.1.0
    command:
    - /bin/bash
    - -c
    - |
      cleos wallet create
      cleos wallet import --private-key $$EOS_PRIVATE 
      cleos wallet import --private-key 5KQwrPbwdL6PhXujxW37FSSQZ1JiwsST4cqQzDeyXtP79zkvFD3 #default eosio account private key
      cleos -u $$EOS_API create account eosio master $$EOS_PUBLIC
    environment:
    - EOS_API=http://server:8888 # url on which nodeos is running
    - EOS_PRIVATE=5KRuLTUU5pzPBhVPv2JkgXGtRoCM8g36PRCAxaCANYwJ7DH15tn # key used to sign master account
    - EOS_PUBLIC=EOS8Bi2k2R4Zv3Go2FEBAM6X8nu7aDPBDWGZeNhewhQZQThe61nc7 # key used to create master account (public key of $EOS_PRIVATE)
    tty: true
## Cleos interface
  tools:
    image: eosio/eos-dev:v1.1.0
    command:
    - bash
    environment:
    - EOS_API=http://server:8888 # url on which nodeos is running
    tty: true
## Deploy contract
  deploy:
    image: iryo
    command:
    - go
    - run
    - main.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/deploy_eos_contract
    environment:
    - EOS_API=http://server:8888
    - EOS_ACCOUNT=iryo
    - EOS_CONTRACT_NAME=iryo
    - EOS_TOKEN_ACCOUNT=iryo.token
    - EOS_TOKEN_NAME=eosio.token
    - EOS_PRIVATE=5KRuLTUU5pzPBhVPv2JkgXGtRoCM8g36PRCAxaCANYwJ7DH15tn # key with which go-eos signs actions

  api:
    image: iryo
    command:
    - go
    - run
    - main.go
    - handlers.go
    - wshandlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/api
    environment:
    - IRYO_ADDR=0.0.0.0:8000
    - EOS_API=http://server:8888
    - EOS_CONTRACT_NAME=iryo
    - EOS_TOKEN_ACCOUNT=iryo.token
    - DEBUG=1
    - EOS_PRIVATE=5KRuLTUU5pzPBhVPv2JkgXGtRoCM8g36PRCAxaCANYwJ7DH15tn
    ports:
    - 8000:8000
  ## patient server
  patient1:
    image: iryo
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/eos_patient
    environment:
    - IRYO_ADDR=api:8000
    - EOS_API=http://server:8888
    - EOS_CONTRACT_NAME=iryo
    - EOS_PRIVATE=5KEVFho54n5B2sHuNL7sDgbbgFNGcGhtpJqUB3XMmkHMz5fGrqz # key with which go-eos signs actions
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9001:9000

  patient2:
    image: iryo
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/eos_patient
    environment:
    - IRYO_ADDR=api:8000
    - EOS_API=http://server:8888
    - EOS_CONTRACT_NAME=iryo
    - EOS_PRIVATE=5KF9vHG4jc7eZXD84m2RmZLgbcBYuT55nRcBaMrwFXAhBNWDHD5 # key with which go-eos signs actions
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9002:9000
  ## Doctor
  doctor1:
    image: iryo
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/eos_doctor
    environment:
    - EOS_API=http://server:8888
    - IRYO_ADDR=api:8000
    - EOS_CONTRACT_NAME=iryo
    - EOS_PRIVATE=5JvuPL6XJ4cRKvB6wuXxDHveMkyfBRPLtB4oRFiijsyto1f7peV # key with which go-eos signs actions
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9003:9000
  ## Doctor
  doctor2:
    image: iryo
    command:
    - go
    - run
    - main.go
    - handlers.go
    volumes:
    - ./:/go/src/github.com/iryonetwork/network-poc
    working_dir: /go/src/github.com/iryonetwork/network-poc/cmd/eos_doctor
    environment:
    - EOS_API=http://server:8888
    - IRYO_ADDR=api:8000
    - EOS_CONTRACT_NAME=iryo
    - EOS_PRIVATE=5KTTcXKdJeG1FgJv5UUhWysWgaDsjbsVCoMizpjSxhfwNswKyQF # key with which go-eos signs actions
    - CLIENT_ADDR=0.0.0.0:9000
    - DEBUG=1
    ports:
    - 9004:9000

volumes:
  devchain:
