kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: api
  labels:
    system: iryopoc
    type: service
    component: api
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: api
  template:
    metadata:
      labels:
        name: api
    spec:
      containers:
      - name: api
        image: "{{ .Values.apiDockerImage }}"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{.Values.serverPort }}
        command: [ "/iryo/api" ]
        env:
          - name: IRYO_ADDR
            value: 0.0.0.0:{{ .Values.serverPort }}
          - name: DEBUG
            value: "1"
          - name: EOS_ACCOUNT_FORMAT
            value: '[a-z1-5]{8}iryo'
          - name: EOS_REQUIRES_RAM
            value: "1"
          - name: DATA_PATH
            value: /data/
          - name: EOS_CONTRACT_NAME
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: contractName
          - name: EOS_CONTRACT_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: contractAccount
          - name: EOS_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: contractName
          - name: EOS_PRIVATE
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: privateKey
          - name: EOS_API
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: apiHost
        volumeMounts:
          - mountPath: /data
            name: data
          - mountPath: /tmp
            name: tmp

      volumes:
        - name: data
          persistentVolumeClaim:
            claimName: api-storage
        - name: tmp
          emptyDir: {}
---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: patient
  labels:
    system: iryopoc
    type: service
    component: patient
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: patient
  template:
    metadata:
      labels:
        name: patient
    spec:
      containers:
      - name: patient
        image: "{{ .Values.clientDockerImage }}"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.serverPort }}
        command: [ "/iryo/client" ]
        env:
          - name: CLIENT_ADDR
            value: 0.0.0.0:{{ .Values.serverPort }}
          - name: IRYO_ADDR
            value: http://api.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.serverPort }}
          - name: DEBUG
            value: "1"
          - name: DATA_PATH
            value: /data/
          - name: CLIENT_TYPE
            value: Patient
          - name: EOS_CONTRACT_NAME
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: contractName
          - name: EOS_CONTRACT_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: contractAccount
          - name: EOS_API
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: apiHost
---
kind: Deployment
apiVersion: extensions/v1beta1

metadata:
  name: doctor
  labels:
    system: iryopoc
    type: service
    component: doctor
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0
      maxSurge: 3
  selector:
    matchLabels:
      name: doctor
  template:
    metadata:
      labels:
        name: doctor
    spec:
      containers:
      - name: doctor
        image: "{{ .Values.clientDockerImage }}"
        imagePullPolicy: Always
        ports:
          - name: http
            containerPort: {{ .Values.serverPort }}
        command: [ "/iryo/client" ]
        env:
          - name: CLIENT_ADDR
            value: 0.0.0.0:{{ .Values.serverPort }}
          - name: IRYO_ADDR
            value: http://api.{{ .Release.Namespace }}.svc.cluster.local:{{ .Values.serverPort }}
          - name: DEBUG
            value: "1"
          - name: DATA_PATH
            value: /data/
          - name: CLIENT_TYPE
            value: Doctor
          - name: EOS_CONTRACT_NAME
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: contractName
          - name: EOS_CONTRACT_ACCOUNT
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: contractAccount
          - name: EOS_API
            valueFrom:
              secretKeyRef:
                name: eos-config
                key: apiHost
