apiVersion: v1
kind: Service
metadata:
  name: api-external-name
  labels:
    system: iryopoc
    component: api
spec:
  type: ExternalName
  externalName: api.{{ .Release.Namespace }}.svc.cluster.local
  ports:
    - name: http
      port: {{ .Values.serverPort }}
      targetPort: http
