kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: api-storage
  labels:
    system: iryopoc
    type: storage
    component: api
  annotations:
    helm.sh/resource-policy: keep
spec:
  accessModes:
    - "ReadWriteOnce"
  resources:
    requests:
      storage: "{{ .Values.storageSize }}"
