apiVersion: v1
kind: Secret
metadata:
  name: eos-config
  labels:
    system: iryopoc
type: Opaque
data:
  privateKey: {{ default "" .Values.eos.privateKey | b64enc | quote }}
  contractName: {{ default "" .Values.eos.contractName | b64enc | quote }}
  contractAccount: {{ default "" .Values.eos.contractAccount | b64enc | quote }}
  apiHost: {{ default "" .Values.eos.apiHost | b64enc | quote }}
